//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Land.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferCustomerWishlist
    {
        public int Id { get; set; }
        public int Offer_ID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Offers Offer { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
