//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Land.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Rating_Id { get; set; }
        public string Comment { get; set; }
        public int ProductID { get; set; }
        public double RatingScore { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
