//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Land.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishListLineItems
    {
        public int Wish_Line_ID { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public int wishlistId { get; set; }
        public int ProductID { get; set; }
    
        public virtual wishlist wishlist { get; set; }
        public virtual Product Product { get; set; }
    }
}
